<?php

/**
* Inheritance: no
* Variants: no


Fields Summary:
- title [input]
- author [input]
- coverView [checkbox]
- releaseDate [datetime]
- content [wysiwyg]
- coverImage [hotspotimage]
- authorImage [hotspotimage]
- interestedTitle [input]
- InterestedList [manyToManyObjectRelation]
- file [link]
- seoTitle [input]
- seoDescription [textarea]
- tags [textarea]
- videoTime [input]
- detailVideo [video]
*/


return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'id' => '12',
   'name' => 'News',
   'description' => '',
   'creationDate' => 0,
   'modificationDate' => 1690814397,
   'userOwner' => 2,
   'userModification' => 59,
   'parentClass' => '',
   'implementsInterfaces' => '',
   'listingParentClass' => '',
   'useTraits' => '',
   'listingUseTraits' => '',
   'encryption' => false,
   'encryptedTables' => 
  array (
  ),
   'allowInherit' => false,
   'allowVariants' => false,
   'showVariants' => false,
   'fieldDefinitions' => 
  array (
  ),
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'layout' => NULL,
     'border' => false,
     'name' => 'pimcore_root',
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => 0,
     'height' => 0,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
         'fieldtype' => 'tabpanel',
         'border' => false,
         'tabPosition' => NULL,
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => 'Layout',
         'width' => '',
         'height' => '',
         'collapsible' => false,
         'collapsed' => false,
         'bodyStyle' => '',
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'BaseData',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Base Data',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => 600,
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'title',
                 'title' => 'Title',
                 'tooltip' => '',
                 'mandatory' => true,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => 400,
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'author',
                 'title' => 'Author',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Checkbox::__set_state(array(
                 'fieldtype' => 'checkbox',
                 'defaultValue' => 0,
                 'name' => 'coverView',
                 'title' => 'Featured Item',
                 'tooltip' => 'Appear as Featured Item in News & Announcements listing page',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              3 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Datetime::__set_state(array(
                 'fieldtype' => 'datetime',
                 'queryColumnType' => 'bigint(20)',
                 'columnType' => 'bigint(20)',
                 'defaultValue' => NULL,
                 'useCurrentDate' => false,
                 'name' => 'releaseDate',
                 'title' => 'Published Date',
                 'tooltip' => '',
                 'mandatory' => true,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              4 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Wysiwyg::__set_state(array(
                 'fieldtype' => 'wysiwyg',
                 'width' => '',
                 'height' => '',
                 'toolbarConfig' => '',
                 'excludeFromSearchIndex' => false,
                 'maxCharacters' => '',
                 'name' => 'content',
                 'title' => 'Content',
                 'tooltip' => '',
                 'mandatory' => true,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 150,
             'labelAlign' => 'left',
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Media',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Image',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Hotspotimage::__set_state(array(
                 'fieldtype' => 'hotspotimage',
                 'queryColumnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'columnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'ratioX' => NULL,
                 'ratioY' => NULL,
                 'predefinedDataTemplates' => '',
                 'name' => 'coverImage',
                 'title' => 'Cover',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => true,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'width' => 600,
                 'height' => '',
                 'uploadPath' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Hotspotimage::__set_state(array(
                 'fieldtype' => 'hotspotimage',
                 'queryColumnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'columnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'ratioX' => NULL,
                 'ratioY' => NULL,
                 'predefinedDataTemplates' => '',
                 'name' => 'authorImage',
                 'title' => 'Author',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => true,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'width' => 600,
                 'height' => '',
                 'uploadPath' => '',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
          2 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Interested',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Related Content',
             'width' => 1200,
             'height' => 270,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => 400,
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'interestedTitle',
                 'title' => 'Title',
                 'tooltip' => 'If field is left empty, page will display the default title "Also Worth Watching/Reading"',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyObjectRelation::__set_state(array(
                 'fieldtype' => 'manyToManyObjectRelation',
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'relationType' => true,
                 'visibleFields' => 
                array (
                ),
                 'allowToCreateNewObject' => false,
                 'optimizedAdminLoading' => false,
                 'enableTextSelection' => false,
                 'visibleFieldDefinitions' => 
                array (
                ),
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'News',
                  ),
                  1 => 
                  array (
                    'classes' => 'Events',
                  ),
                  2 => 
                  array (
                    'classes' => 'Course',
                  ),
                  3 => 
                  array (
                    'classes' => 'Articles',
                  ),
                  4 => 
                  array (
                    'classes' => 'Business',
                  ),
                  5 => 
                  array (
                    'classes' => 'CaseStudy',
                  ),
                  6 => 
                  array (
                    'classes' => 'PatentAnalytic',
                  ),
                  7 => 
                  array (
                    'classes' => 'WebinarRecordings',
                  ),
                  8 => 
                  array (
                    'classes' => 'Shares',
                  ),
                ),
                 'pathFormatterClass' => '',
                 'name' => 'InterestedList',
                 'title' => 'Content',
                 'tooltip' => 'To select objects to be displayed at the right component "Also Worth Watching/Reading":

1. Click the Search icon and key in the page title or
2. Pull any objects under "Data Objects"',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 150,
             'labelAlign' => 'left',
          )),
          3 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Resources',
             'type' => NULL,
             'region' => NULL,
             'title' => 'CTA',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Link::__set_state(array(
                 'fieldtype' => 'link',
                 'name' => 'file',
                 'title' => 'Download',
                 'tooltip' => 'For the purple bottom CTA

1. Insert CTA Title at the "Text" field
2. Insert URL at the "Path" field',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 50,
             'labelAlign' => 'left',
          )),
          4 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'SEO & Setting',
             'type' => NULL,
             'region' => NULL,
             'title' => 'SEO & Setting',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'seoTitle',
                 'title' => 'Title',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state(array(
                 'fieldtype' => 'textarea',
                 'width' => '',
                 'height' => '',
                 'maxLength' => NULL,
                 'showCharCount' => false,
                 'excludeFromSearchIndex' => false,
                 'name' => 'seoDescription',
                 'title' => 'Description',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state(array(
                 'fieldtype' => 'textarea',
                 'width' => '',
                 'height' => '',
                 'maxLength' => NULL,
                 'showCharCount' => false,
                 'excludeFromSearchIndex' => false,
                 'name' => 'tags',
                 'title' => 'Keywords',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 0,
             'labelAlign' => 'left',
          )),
          5 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Video',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Video',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'videoTime',
                 'title' => 'Duration',
                 'tooltip' => 'Manually key in the video duration to display at the bottom right of the video.

Format: 00h 00m 00s',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => NULL,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Video::__set_state(array(
                 'fieldtype' => 'video',
                 'width' => 800,
                 'height' => 600,
                 'name' => 'detailVideo',
                 'title' => 'URL',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => NULL,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
        ),
         'locked' => false,
         'blockedVarsForExport' => 
        array (
        ),
      )),
    ),
     'locked' => false,
     'blockedVarsForExport' => 
    array (
    ),
     'icon' => NULL,
     'labelWidth' => 100,
     'labelAlign' => 'left',
  )),
   'icon' => '',
   'previewUrl' => '',
   'group' => 'Events',
   'showAppLoggerTab' => false,
   'linkGeneratorReference' => '',
   'previewGeneratorReference' => '',
   'compositeIndices' => 
  array (
  ),
   'generateTypeDeclarations' => true,
   'showFieldLookup' => false,
   'propertyVisibility' => 
  array (
    'grid' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
    'search' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
  ),
   'enableGridLocking' => false,
   'dao' => NULL,
   'blockedVarsForExport' => 
  array (
  ),
));
