<?php

/**
* Inheritance: no
* Variants: no


Fields Summary:
- title [input]
- eventType [select]
- topic [select]
- venue [select]
- venueText [input]
- cost [select]
- proficiency [select]
- audience [select]
- content [wysiwyg]
- planing [fieldcollections]
- interestedTitle [input]
- interestedList [manyToManyObjectRelation]
- guestsData [block]
-- name [input]
-- institution [input]
-- position [input]
-- detailUrl [input]
-- individualResume [wysiwyg]
-- profilePhoto [hotspotimage]
- coverImage [hotspotimage]
- email [input]
- regsiterUrl [input]
- seoTitle [input]
- seoDescription [textarea]
- tags [textarea]
- videoTime [input]
- detailVideo [video]
*/


return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'id' => '8',
   'name' => 'Events',
   'description' => '',
   'creationDate' => 0,
   'modificationDate' => 1690814395,
   'userOwner' => 2,
   'userModification' => 59,
   'parentClass' => '',
   'implementsInterfaces' => '',
   'listingParentClass' => '',
   'useTraits' => '',
   'listingUseTraits' => '',
   'encryption' => false,
   'encryptedTables' => 
  array (
  ),
   'allowInherit' => false,
   'allowVariants' => false,
   'showVariants' => false,
   'fieldDefinitions' => 
  array (
  ),
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'layout' => NULL,
     'border' => false,
     'name' => 'pimcore_root',
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => 0,
     'height' => 0,
     'collapsible' => false,
     'collapsed' => false,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
         'fieldtype' => 'tabpanel',
         'border' => false,
         'tabPosition' => NULL,
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => 'Layout',
         'width' => '',
         'height' => '',
         'collapsible' => false,
         'collapsed' => false,
         'bodyStyle' => '',
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Region::__set_state(array(
             'fieldtype' => 'region',
             'name' => 'BaseData',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Base Data',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
                 'fieldtype' => 'panel',
                 'layout' => NULL,
                 'border' => false,
                 'name' => 'Base Data',
                 'type' => NULL,
                 'region' => 'center',
                 'title' => 'Base Data',
                 'width' => '50%',
                 'height' => '',
                 'collapsible' => false,
                 'collapsed' => false,
                 'bodyStyle' => '',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'title',
                     'title' => 'Title',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  1 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => 'Seminar',
                        'value' => 'Seminar',
                      ),
                      1 => 
                      array (
                        'key' => 'Course',
                        'value' => 'Course',
                      ),
                      2 => 
                      array (
                        'key' => 'Webinar',
                        'value' => 'Webinar',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'eventType',
                     'title' => 'Event Type',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  2 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => '',
                        'value' => 'All Topics',
                      ),
                      1 => 
                      array (
                        'key' => 'Intangible Assets (IA)',
                        'value' => ' Intangible Assets (IA)',
                      ),
                      2 => 
                      array (
                        'key' => 'Intellectual Property (IP)',
                        'value' => 'Intellectual Property (IP)',
                      ),
                      3 => 
                      array (
                        'key' => ' IP Management / Strategy',
                        'value' => ' IP Management / Strategy',
                      ),
                      4 => 
                      array (
                        'key' => 'Business',
                        'value' => 'Business',
                      ),
                      5 => 
                      array (
                        'key' => 'Legal',
                        'value' => 'Legal',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'topic',
                     'title' => 'Topic',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  3 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => 'In-Person',
                        'value' => 'In-Person',
                      ),
                      1 => 
                      array (
                        'key' => 'Online Live Stream',
                        'value' => 'Online Live Stream',
                      ),
                      2 => 
                      array (
                        'key' => 'Online (Self Learning)',
                        'value' => 'Online (Self Learning)',
                      ),
                      3 => 
                      array (
                        'key' => 'Online Live Stream + Self Learning',
                        'value' => 'Online Live Stream + Self Learning',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'venue',
                     'title' => 'Venue',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  4 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'venueText',
                     'title' => 'Venue Text',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  5 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => 'Free',
                        'value' => 'Free',
                      ),
                      1 => 
                      array (
                        'key' => 'Paid',
                        'value' => 'Paid',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'cost',
                     'title' => 'Cost',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  6 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => 'Beginner',
                        'value' => 'Beginner',
                      ),
                      1 => 
                      array (
                        'key' => 'Intermediate',
                        'value' => 'Intermediate',
                      ),
                      2 => 
                      array (
                        'key' => 'Professional',
                        'value' => 'Professional',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'proficiency',
                     'title' => 'Proficiency',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  7 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Select::__set_state(array(
                     'fieldtype' => 'select',
                     'options' => 
                    array (
                      0 => 
                      array (
                        'key' => '',
                        'value' => 'All',
                      ),
                      1 => 
                      array (
                        'key' => 'IP Professionals',
                        'value' => 'IP Professionals',
                      ),
                      2 => 
                      array (
                        'key' => 'Public Agencies/Officers',
                        'value' => 'Public Agencies/Officers',
                      ),
                      3 => 
                      array (
                        'key' => 'Enterprises/Individuals',
                        'value' => 'Enterprises/Individuals',
                      ),
                      4 => 
                      array (
                        'key' => 'Graduate Studies',
                        'value' => 'Graduate Studies',
                      ),
                    ),
                     'width' => '',
                     'defaultValue' => '',
                     'optionsProviderClass' => '',
                     'optionsProviderData' => '',
                     'columnLength' => 190,
                     'dynamicOptions' => false,
                     'name' => 'audience',
                     'title' => 'Audience',
                     'tooltip' => '',
                     'mandatory' => true,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
                 'icon' => '',
                 'labelWidth' => 150,
                 'labelAlign' => 'left',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
                 'fieldtype' => 'panel',
                 'layout' => NULL,
                 'border' => false,
                 'name' => 'ContentData',
                 'type' => NULL,
                 'region' => 'east',
                 'title' => 'ContentData',
                 'width' => '50%',
                 'height' => '',
                 'collapsible' => false,
                 'collapsed' => false,
                 'bodyStyle' => '',
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Wysiwyg::__set_state(array(
                     'fieldtype' => 'wysiwyg',
                     'width' => '',
                     'height' => 400,
                     'toolbarConfig' => '',
                     'excludeFromSearchIndex' => false,
                     'maxCharacters' => '',
                     'name' => 'content',
                     'title' => 'Content',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                  )),
                ),
                 'locked' => false,
                 'blockedVarsForExport' => 
                array (
                ),
                 'icon' => '',
                 'labelWidth' => 0,
                 'labelAlign' => 'left',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'EventsPlannig',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Event Schedule',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections::__set_state(array(
                 'fieldtype' => 'fieldcollections',
                 'allowedTypes' => 
                array (
                  0 => 'ProgramPlanning',
                ),
                 'lazyLoading' => true,
                 'maxItems' => '',
                 'disallowAddRemove' => false,
                 'disallowReorder' => false,
                 'collapsed' => false,
                 'collapsible' => false,
                 'border' => false,
                 'name' => 'planing',
                 'title' => 'Schedule',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 300,
             'labelAlign' => 'left',
          )),
          2 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Interested',
             'type' => NULL,
             'region' => NULL,
             'title' => 'You May Also Like',
             'width' => 1200,
             'height' => 270,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => 400,
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'interestedTitle',
                 'title' => 'Title',
                 'tooltip' => 'If field is left empty, page will display the default title "Also Worth Watching/Reading"',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\ManyToManyObjectRelation::__set_state(array(
                 'fieldtype' => 'manyToManyObjectRelation',
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'relationType' => true,
                 'visibleFields' => 'published,classname,id,key,fullpath',
                 'allowToCreateNewObject' => false,
                 'optimizedAdminLoading' => false,
                 'enableTextSelection' => false,
                 'visibleFieldDefinitions' => 
                array (
                ),
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'WebinarRecordings',
                  ),
                  1 => 
                  array (
                    'classes' => 'PatentAnalytic',
                  ),
                  2 => 
                  array (
                    'classes' => 'CaseStudy',
                  ),
                  3 => 
                  array (
                    'classes' => 'Business',
                  ),
                  4 => 
                  array (
                    'classes' => 'Articles',
                  ),
                  5 => 
                  array (
                    'classes' => 'News',
                  ),
                  6 => 
                  array (
                    'classes' => 'Events',
                  ),
                  7 => 
                  array (
                    'classes' => 'CoursesDemand',
                  ),
                  8 => 
                  array (
                    'classes' => 'Course',
                  ),
                ),
                 'pathFormatterClass' => '',
                 'name' => 'interestedList',
                 'title' => 'You May Also Like',
                 'tooltip' => 'To feature at the bottom slider of the page.',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
          3 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Pane',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Speaker/Trainer Info',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Block::__set_state(array(
                 'fieldtype' => 'block',
                 'lazyLoading' => false,
                 'disallowAddRemove' => false,
                 'disallowReorder' => false,
                 'collapsible' => false,
                 'collapsed' => false,
                 'maxItems' => NULL,
                 'styleElement' => '',
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'name',
                     'title' => 'Name',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  1 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'institution',
                     'title' => 'Company',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  2 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'position',
                     'title' => 'Title',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  3 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                     'fieldtype' => 'input',
                     'width' => '',
                     'defaultValue' => NULL,
                     'columnLength' => 190,
                     'regex' => '',
                     'unique' => false,
                     'showCharCount' => false,
                     'name' => 'detailUrl',
                     'title' => 'URL',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'defaultValueGenerator' => '',
                  )),
                  4 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Wysiwyg::__set_state(array(
                     'fieldtype' => 'wysiwyg',
                     'width' => '',
                     'height' => '',
                     'toolbarConfig' => '',
                     'excludeFromSearchIndex' => false,
                     'maxCharacters' => '',
                     'name' => 'individualResume',
                     'title' => 'Description',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                  )),
                  5 => 
                  Pimcore\Model\DataObject\ClassDefinition\Data\Hotspotimage::__set_state(array(
                     'fieldtype' => 'hotspotimage',
                     'queryColumnType' => 
                    array (
                      'image' => 'int(11)',
                      'hotspots' => 'text',
                    ),
                     'columnType' => 
                    array (
                      'image' => 'int(11)',
                      'hotspots' => 'text',
                    ),
                     'ratioX' => NULL,
                     'ratioY' => NULL,
                     'predefinedDataTemplates' => '',
                     'name' => 'profilePhoto',
                     'title' => 'Profile Photo',
                     'tooltip' => '',
                     'mandatory' => false,
                     'noteditable' => false,
                     'index' => false,
                     'locked' => false,
                     'style' => '',
                     'permissions' => NULL,
                     'datatype' => 'data',
                     'relationType' => false,
                     'invisible' => false,
                     'visibleGridView' => false,
                     'visibleSearch' => false,
                     'forbiddenNames' => 
                    array (
                      0 => 'id',
                      1 => 'key',
                      2 => 'path',
                      3 => 'type',
                      4 => 'index',
                      5 => 'classname',
                      6 => 'creationdate',
                      7 => 'userowner',
                      8 => 'value',
                      9 => 'class',
                      10 => 'list',
                      11 => 'fullpath',
                      12 => 'childs',
                      13 => 'values',
                      14 => 'cachetag',
                      15 => 'cachetags',
                      16 => 'parent',
                      17 => 'published',
                      18 => 'valuefromparent',
                      19 => 'userpermissions',
                      20 => 'dependencies',
                      21 => 'modificationdate',
                      22 => 'usermodification',
                      23 => 'byid',
                      24 => 'bypath',
                      25 => 'data',
                      26 => 'versions',
                      27 => 'properties',
                      28 => 'permissions',
                      29 => 'permissionsforuser',
                      30 => 'childamount',
                      31 => 'apipluginbroker',
                      32 => 'resource',
                      33 => 'parentClass',
                      34 => 'definition',
                      35 => 'locked',
                      36 => 'language',
                      37 => 'omitmandatorycheck',
                      38 => 'idpath',
                      39 => 'object',
                      40 => 'fieldname',
                      41 => 'property',
                      42 => 'parentid',
                      43 => 'children',
                      44 => 'scheduledtasks',
                    ),
                     'blockedVarsForExport' => 
                    array (
                    ),
                     'width' => '',
                     'height' => '',
                     'uploadPath' => '',
                  )),
                ),
                 'layout' => NULL,
                 'referencedFields' => 
                array (
                ),
                 'fieldDefinitionsCache' => NULL,
                 'name' => 'guestsData',
                 'title' => 'Speaker/Trainer',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
          4 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Resources',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Image',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Hotspotimage::__set_state(array(
                 'fieldtype' => 'hotspotimage',
                 'queryColumnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'columnType' => 
                array (
                  'image' => 'int(11)',
                  'hotspots' => 'text',
                ),
                 'ratioX' => NULL,
                 'ratioY' => NULL,
                 'predefinedDataTemplates' => '',
                 'name' => 'coverImage',
                 'title' => 'Cover Image',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'width' => 600,
                 'height' => '',
                 'uploadPath' => '',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
          5 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Contact',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Registration Info',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'email',
                 'title' => 'Email Address',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 200,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'regsiterUrl',
                 'title' => 'Registration URL',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
          6 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'SEO & Setting',
             'type' => NULL,
             'region' => NULL,
             'title' => 'SEO & Setting',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'seoTitle',
                 'title' => 'Title',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state(array(
                 'fieldtype' => 'textarea',
                 'width' => '',
                 'height' => '',
                 'maxLength' => NULL,
                 'showCharCount' => false,
                 'excludeFromSearchIndex' => false,
                 'name' => 'seoDescription',
                 'title' => 'Description',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Textarea::__set_state(array(
                 'fieldtype' => 'textarea',
                 'width' => '',
                 'height' => '',
                 'maxLength' => NULL,
                 'showCharCount' => false,
                 'excludeFromSearchIndex' => false,
                 'name' => 'tags',
                 'title' => 'Keywords',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 0,
             'labelAlign' => 'left',
          )),
          7 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'layout' => NULL,
             'border' => false,
             'name' => 'Video',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Video',
             'width' => '',
             'height' => '',
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => '',
                 'defaultValue' => NULL,
                 'columnLength' => 190,
                 'regex' => '',
                 'unique' => false,
                 'showCharCount' => false,
                 'name' => 'videoTime',
                 'title' => 'Duration',
                 'tooltip' => 'Manually key in the video duration to display at the bottom right of the video.

Format: 00h 00m 00s',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => NULL,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
                 'defaultValueGenerator' => '',
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Video::__set_state(array(
                 'fieldtype' => 'video',
                 'width' => 800,
                 'height' => 600,
                 'name' => 'detailVideo',
                 'title' => 'URL',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => false,
                 'index' => false,
                 'locked' => NULL,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
                 'forbiddenNames' => 
                array (
                  0 => 'id',
                  1 => 'key',
                  2 => 'path',
                  3 => 'type',
                  4 => 'index',
                  5 => 'classname',
                  6 => 'creationdate',
                  7 => 'userowner',
                  8 => 'value',
                  9 => 'class',
                  10 => 'list',
                  11 => 'fullpath',
                  12 => 'childs',
                  13 => 'values',
                  14 => 'cachetag',
                  15 => 'cachetags',
                  16 => 'parent',
                  17 => 'published',
                  18 => 'valuefromparent',
                  19 => 'userpermissions',
                  20 => 'dependencies',
                  21 => 'modificationdate',
                  22 => 'usermodification',
                  23 => 'byid',
                  24 => 'bypath',
                  25 => 'data',
                  26 => 'versions',
                  27 => 'properties',
                  28 => 'permissions',
                  29 => 'permissionsforuser',
                  30 => 'childamount',
                  31 => 'apipluginbroker',
                  32 => 'resource',
                  33 => 'parentClass',
                  34 => 'definition',
                  35 => 'locked',
                  36 => 'language',
                  37 => 'omitmandatorycheck',
                  38 => 'idpath',
                  39 => 'object',
                  40 => 'fieldname',
                  41 => 'property',
                  42 => 'parentid',
                  43 => 'children',
                  44 => 'scheduledtasks',
                ),
                 'blockedVarsForExport' => 
                array (
                ),
              )),
            ),
             'locked' => false,
             'blockedVarsForExport' => 
            array (
            ),
             'icon' => '',
             'labelWidth' => 200,
             'labelAlign' => 'left',
          )),
        ),
         'locked' => false,
         'blockedVarsForExport' => 
        array (
        ),
      )),
    ),
     'locked' => false,
     'blockedVarsForExport' => 
    array (
    ),
     'icon' => NULL,
     'labelWidth' => 100,
     'labelAlign' => 'left',
  )),
   'icon' => '',
   'previewUrl' => '',
   'group' => 'Events',
   'showAppLoggerTab' => false,
   'linkGeneratorReference' => '',
   'previewGeneratorReference' => '',
   'compositeIndices' => 
  array (
  ),
   'generateTypeDeclarations' => true,
   'showFieldLookup' => false,
   'propertyVisibility' => 
  array (
    'grid' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
    'search' => 
    array (
      'id' => true,
      'key' => false,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
  ),
   'enableGridLocking' => false,
   'dao' => NULL,
   'blockedVarsForExport' => 
  array (
  ),
));
