pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    advisoryOverview:
                        items: {  }
                        medias: {  }
                        name: advisoryOverview
                        description: ''
                        group: Advisory
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292974
                        creationDate: 1718292968
                        preserveAnimation: false
