pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    background:
                        items: {  }
                        medias: {  }
                        name: background
                        description: ''
                        group: Public
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292858
                        creationDate: 1718292848
                        preserveAnimation: false
