pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    BookIaChat:
                        items: {  }
                        medias: {  }
                        name: BookIaChat
                        description: ''
                        group: Public
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1719328441
                        creationDate: 1718895760
                        preserveAnimation: false
