pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    Courses:
                        items: {  }
                        medias: {  }
                        name: Courses
                        description: ''
                        group: Academy
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292944
                        creationDate: 1718292939
                        preserveAnimation: false
