pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    coverImg:
                        items: {  }
                        medias: {  }
                        name: coverImg
                        description: ''
                        group: Public
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292835
                        creationDate: 1718292825
                        preserveAnimation: false
