pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    NewsAnnouncementsLatest:
                        items: {  }
                        medias: {  }
                        name: NewsAnnouncementsLatest
                        description: ''
                        group: Events
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292997
                        creationDate: 1718292993
                        preserveAnimation: false
