pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    ProfilePhoto:
                        items: {  }
                        medias: {  }
                        name: ProfilePhoto
                        description: ''
                        group: Public
                        format: PNG
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1718292696
                        creationDate: 1718292687
                        preserveAnimation: false
